import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    height: '100%',
    backgroundColo: 'grey',
  },
  title: {
    height: 50,
    alignItems: 'center',
    padding: 5,
  },
  containerInput: {
    marginHorizontal: 10,
    marginVertical: 2,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  inputWaktu:{
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  listContainer:{
    display: 'flex',
    flexWrap:'wrap',
    flexDirection: 'row',
  },
  form: {
    height: 500,
    borderRadius: 10,
    backgroundColor: 'white',
    borderColor: '#171717',
    elevation: 1,
    shadowOpacity: 1,
    shadowRadius: 1,
    margin: 10,
    paddingTop: 10,
  },
  buttonField: {
    width: '100%',
    height: 60,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  
  button: {
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 5,
    elevation: 1,
    shadowOpacity: 1,
    shadowRadius: 1,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  dropdown: {
    height: 40,
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    color: 'black',
  },
  labelDropdown: {
    color: 'black',
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: -2,
    zIndex: 999,
    paddingHorizontal: 5,
    fontSize: 10,
  },
  placeholderStyle: {
    fontSize: 14,
    color: 'black',
  },
  selectedTextStyle: {
    fontSize: 14,
    color: 'black',
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  label: {
    color: 'black',
    fontFamily: 'Montserrat Bold 700',
    fontSize: 14,
    width: '19%',
  },
  input: {
    color: 'black',
    width: '100%',
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  buttonAdd: {
    width: '32%',
    height: 40,
    borderRadius: 5,
    alignItems: 'center',
    backgroundColor: '#09322D',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  timePicker:{
    width: '65%',
  },
  buttonAddField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectedStyle: {
    borderRadius: 5,
  },
  valueWaktu:{
    // backgroundColor: 'red',
    width: '30%',
    marginVertical: 5,
    marginHorizontal: 5,
    padding: 10,
    backgroundColor: 'white',
    borderColor: '#171717',
    elevation: 2,
    shadowOpacity: 5,
    shadowRadius: 2,
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  
});

export default styles;